.SILENT:

all: launch

launch:
	\echo -e "[${BLUE}INFO${RESET}] Start the dump.sh file..."
	\sh dump.sh $(ARG) $(FORCE) #vendor-id device-id cancel-vendor-id cancel-device-id // focerd-uuid

.PHONY: all
