##
## EPITECH PROJECT, 2024
## Fedora dump script
## File description:
## Makefile to start sh script
##

# Color definition
RED := \033[31m
GREEN := \033[32m
YELLOW := \033[33m
BLUE := \033[34m
MAGENTA := \033[35m
CYAN := \033[36m
RESET := \033[0m

all: launch

launch:
	@echo -e "----------------------[${MAGENTA}START${RESET}]----------------------"
	@echo -e "[${BLUE}INFO${RESET}] Start the dump.sh file..."
	@\sh dump.sh $(ARG) $(FORCE) #vendor-id device-id cancel-vendor-id cancel-device-id // 
	@echo -e "-----------------------[${MAGENTA}END${RESET}]-----------------------"

.PHONY: all
